version: "1.0.0"

services:
  database:
    image: postgres:15
    container_name: atelie
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: atelie
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '7777:8080'
    depends_on:
      - database
volumes:
  postgres_data:
